// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBeDV2BRR1-ltqwqUs2sNFw7jrstlhftFQ',
    appId: '1:86256742736:web:4cea9b352d284978797c55',
    messagingSenderId: '86256742736',
    projectId: 'wasil-65121',
    authDomain: 'wasil-65121.firebaseapp.com',
    storageBucket: 'wasil-65121.firebasestorage.app',
    measurementId: 'G-FENFKVT41S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2yJOWG3jNFWrj9xSX1Lbv0DNtyAPzoHA',
    appId: '1:86256742736:android:bbb969f8651e9ff4797c55',
    messagingSenderId: '86256742736',
    projectId: 'wasil-65121',
    storageBucket: 'wasil-65121.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJ7m3m863UWsBshMRiwJk88ndyxa0E6jk',
    appId: '1:86256742736:ios:15a9cbff0d85801d797c55',
    messagingSenderId: '86256742736',
    projectId: 'wasil-65121',
    storageBucket: 'wasil-65121.firebasestorage.app',
    iosBundleId: 'com.example.storeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJ7m3m863UWsBshMRiwJk88ndyxa0E6jk',
    appId: '1:86256742736:ios:15a9cbff0d85801d797c55',
    messagingSenderId: '86256742736',
    projectId: 'wasil-65121',
    storageBucket: 'wasil-65121.firebasestorage.app',
    iosBundleId: 'com.example.storeApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBeDV2BRR1-ltqwqUs2sNFw7jrstlhftFQ',
    appId: '1:86256742736:web:64646d973223aeb1797c55',
    messagingSenderId: '86256742736',
    projectId: 'wasil-65121',
    authDomain: 'wasil-65121.firebaseapp.com',
    storageBucket: 'wasil-65121.firebasestorage.app',
    measurementId: 'G-KVNXMVM8G8',
  );
}
